[package]
edition      = "2021"
name         = "esp_firmware"
rust-version = "1.86"
version      = "0.1.0"

[[bin]]
name = "esp_firmware"
path = "./src/bin/main.rs"

[dependencies]
defmt = "1.0.1"
# esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal",  features = ["esp32s3"] }
# esp-hal = { version = "=1.1.1", features = [
esp-hal = { git = "https://github.com/esp-rs/esp-hal",  features = [
  "defmt",
  "esp32s3",
  "unstable",
] }

critical-section = "1.2.0"
embedded-io = { version = "0.7.1", features = ["defmt"] }
esp-alloc = { git = "https://github.com/esp-rs/esp-hal",  features = ["defmt"] }
# esp-alloc = { version = "0.10.0", features = ["defmt"] }
esp-radio = { git = "https://github.com/esp-rs/esp-hal",  features = ["unstable", "defmt", "esp32s3", "esp-now"] }
# esp-radio = { version = "0.18.0", features = ["unstable", "defmt", "esp32s3", "esp-now"] }
panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
rtt-target = { version = "0.6.2", features = ["defmt"] }
smoltcp = { version = "0.13.1", default-features = false, features = [
  "defmt",
  "medium-ethernet",
  "multicast",
  "proto-dhcpv4",
  "proto-dns",
  "proto-ipv4",
  "socket-dns",
  "socket-icmp",
  "socket-raw",
  "socket-tcp",
  "socket-udp",
] }
# esp32s3 = "0.35.2"
esp32s3 = { git = "https://github.com/esp-rs/esp-pacs", rev = "131062119" }
embedded-error = "0.6.0"
bitfield = "0.19.2"
crc-any = { version = "3.0.1", default-features = false }
fatfs = { git = "https://github.com/rafalh/rust-fatfs", default-features = false }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal",  features = ["esp32s3", "esp-radio", "defmt"] }
# esp-rtos = { version = "0.3.0", features = ["esp32s3", "esp-radio", "defmt"] }
mbr-nostd = "0.1.0"
static_cell = "2.1.1"

shared = { path = "../shared" }
num_enum = { version = "0.7.6", default-features = false }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false

[features]
logger_print_both = []
