OUTPUT_HEX_FILE := "target/firmware.hex"
PORT := "/dev/ttyACM0"

alias u := upload
alias m := monitor

default:
    just --list

build:
    cargo objcopy --release -- -O ihex {{OUTPUT_HEX_FILE}}

upload: build
    teensy-loader-cli -w -v --mcu=imxrt1062 {{OUTPUT_HEX_FILE}}

monitor:
    minicom -D {{PORT}} && reset
